fix: upgrade to react-native 0.70.12 to fix metro bundler crash with Xcode 14.3 (#3950)
### Description

As the title says.
Applied the changes in this diff:
https://github.com/react-native-community/rn-diff-purge/compare/release/0.70.9..release/0.70.12

See https://github.com/facebook/react-native/issues/36794

This is what I was seeing locally:

```
Error: Unable to resolve module ./Libraries/Components/DatePicker/DatePickerIOS from /Users/jean/src/github.com/valora-inc/wallet/node_modules/react-native/index.js:

None of these files exist:
  * node_modules/react-native/Libraries/Components/DatePicker/DatePickerIOS(.native|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx)
  * node_modules/react-native/Libraries/Components/DatePicker/DatePickerIOS/index(.native|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx)
  15 | import typeof ActivityIndicator from './Libraries/Components/ActivityIndicator/ActivityIndicator';
  16 | import typeof Button from './Libraries/Components/Button';
> 17 | import typeof DatePickerIOS from './Libraries/Components/DatePicker/DatePickerIOS';
     |                                   ^
  18 | import typeof DrawerLayoutAndroid from './Libraries/Components/DrawerAndroid/DrawerLayoutAndroid';
  19 | import typeof FlatList from './Libraries/Lists/FlatList';
  20 | import typeof Image from './Libraries/Image/Image';
    at ModuleResolver.resolveDependency (/Users/jean/src/github.com/valora-inc/wallet/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:152:15)
    at DependencyGraph.resolveDependency (/Users/jean/src/github.com/valora-inc/wallet/node_modules/metro/src/node-haste/DependencyGraph.js:264:43)
    at Object.resolve (/Users/jean/src/github.com/valora-inc/wallet/node_modules/metro/src/lib/transformHelpers.js:170:21)
    at resolveDependencies (/Users/jean/src/github.com/valora-inc/wallet/node_modules/metro/src/DeltaBundler/graphOperations.js:466:33)
    at processModule (/Users/jean/src/github.com/valora-inc/wallet/node_modules/metro/src/DeltaBundler/graphOperations.js:232:31)
    at async addDependency (/Users/jean/src/github.com/valora-inc/wallet/node_modules/metro/src/DeltaBundler/graphOperations.js:361:18)
    at async Promise.all (index 4)
    at async processModule (/Users/jean/src/github.com/valora-inc/wallet/node_modules/metro/src/DeltaBundler/graphOperations.js:279:3)
    at async traverseDependenciesForSingleFile (/Users/jean/src/github.com/valora-inc/wallet/node_modules/metro/src/DeltaBundler/graphOperations.js:221:3)
    at async Promise.all (index 0)

<--- Last few GCs --->

[30477:0x7ff5b0008000] 11965029 ms: Mark-sweep (reduce) 4066.3 (4143.3) -> 4065.6 (4143.8) MB, 3072.4 / 0.1 ms  (average mu = 0.298, current mu = 0.002) allocation failure scavenge might not succeed
[30477:0x7ff5b0008000] 11968093 ms: Mark-sweep (reduce) 4066.8 (4143.8) -> 4066.3 (4144.6) MB, 3059.2 / 0.1 ms  (average mu = 0.175, current mu = 0.001) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10bbc3bf5 node::Abort() (.cold.1) [/Users/jean/.asdf/installs/nodejs/16.15.0/bin/node]
 2: 0x10a8b7349 node::Abort() [/Users/jean/.asdf/installs/nodejs/16.15.0/bin/node]
 3: 0x10a8b74bf node::OnFatalError(char const*, char const*) [/Users/jean/.asdf/installs/nodejs/16.15.0/bin/node]
 4: 0x10aa39987 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/jean/.asdf/installs/nodejs/16.15.0/bin/node]
 5: 0x10aa39923 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/jean/.asdf/installs/nodejs/16.15.0/bin/node]
 6: 0x10abdb005 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/jean/.asdf/installs/nodejs/16.15.0/bin/node]
 7: 0x10abd998c v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/jean/.asdf/installs/nodejs/16.15.0/bin/node]
 8: 0x10abe6230 v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/jean/.asdf/installs/nodejs/16.15.0/bin/node]
 9: 0x10abe62b1 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/jean/.asdf/installs/nodejs/16.15.0/bin/node]
10: 0x10abb3347 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/Users/jean/.asdf/installs/nodejs/16.15.0/bin/node]
11: 0x10af6af4e v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/Users/jean/.asdf/installs/nodejs/16.15.0/bin/node]
12: 0x10b314a19 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/jean/.asdf/installs/nodejs/16.15.0/bin/node]
13: 0x10b2d54c8 Builtins_AsyncFunctionEnter [/Users/jean/.asdf/installs/nodejs/16.15.0/bin/node]
14: 0x10f8f8e42
15: 0x10f9e195e
16: 0x10b2d6dff Builtins_AsyncFunctionAwaitResolveClosure [/Users/jean/.asdf/installs/nodejs/16.15.0/bin/node]
error Command failed with signal "SIGABRT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Test plan

- Tested the metro bundler doesn't crash anymore

### Related issues

- N/A

### Backwards compatibility

Yes